# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.4.0

    working_directory: /tmp/ui

    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install system dependencies
          command: sudo apt-get update && sudo apt-get -y install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libxext6
      - run: 
          name: Install node dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run: 
          name: Run coverage tests
          command: npm run test:coverage
      - run: 
          name: Send coverage reports
          command: npm run codecov
      - run: 
          name: Build static storybook
          command: npm run build:storybook
      - run: 
          name: Run visual tests
          command: npm run test:visual
      - run:
          name: Deploy to now.sh
          command: cd storybook-static && npm install now --no-save && ../node_modules/.bin/now --token $NOW_TOKEN --public && ../node_modules/.bin/now alias dcl-ui --token $NOW_TOKEN

workflows:
  version: 2
  test:
    jobs:
      - test